title: SDAV Exam Project
email: s214588@student.dtu.dk
description: >- # this means to ignore newlines until "baseurl:"
  Data Visualization Exam Project for the DTU course SDAV.
baseurl: "/SDAV_exam_project" # the subpath of your site
url: "https://magdk01.github.io" # the base hostname & protocol for your site
github_username: Magdk01

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji

# Additional settings for data visualization
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections
collections:
  visualizations:
    output: true
    permalink: /visualizations/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: visualizations
    values:
      layout: visualization
      comments: true

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: GitHub
    url: https://github.com/Magdk01/SDAV_exam_project 